steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/terrenceryan', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/terrenceryan']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'terrenceryan', '--image', 'gcr.io/$PROJECT_ID/terrenceryan', '--region', 'us-central1','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/terrenceryan