steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/terrenceryan_test', "-f", 'test.Dockerfile', "."]
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-d', '--name=terrenceryan_test', 'gcr.io/$PROJECT_ID/terrenceryan_test']
- name: 'alpine'
  args: ['bash', '/run_tests.sh']      
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/terrenceryan', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/terrenceryan']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'terrenceryan', '--image', 'gcr.io/$PROJECT_ID/terrenceryan', '--region', 'us-central1','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/terrenceryan