runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|svg))$
  static_files: \1
  upload: .+\.(gif|png|jpg|svg)$
  application_readable: true

- url: /(.+\.(html|css|js|woff|ttf))$
  static_files: \1
  upload: .+\.(html|css|js|woff|ttf)$
  application_readable: true

- url: /assets/css
  static_dir: /assets/css  

- url: /blog/.*
  script: /blog/parse.php

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /(.+)/$
  script: \1/index.php

- url: /(.+)$
  script: \1/index.php 


# Serve php scripts.
- url: /
  script: /index.php  