runtime: php72

handlers:


- url: /assets/css/main.css
  static_dir: /assets/css/main.css



- url: /(.+\.(html|css|js|woff|ttf|txt))$
  static_files: \1
  upload: .+\.(html|css|js|woff|ttf|txt)$


# - url: /blog/post.cfm.*
#   script: /cfmlhandler.php  

# - url: /blog/(.+\.cfm)$
#   script: /cfmlhandler.php   

# - url: /(.+\.cfm)$
#   script: /cfmlhandler.php 

# # Redirect all blog traffic. 
# - url: /blog/.*
#   script: /blog/parse.php

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|svg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|svg|ico)$

# Serve up aby root php scripts.
# - url: /(.+\.php)$
#   script: \1

# # Set subfolder root to index.php
# - url: /(.+)/$
#   script: \1/index.php

# - url: /(.+)$
#   script: \1/index.php 

# Set root to index.php
- url: .*
  script: auto
